### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by heathj** [heathj/gobrowse#10]
When I started this project, I wanted this to be a reference implementation so that included errors. I'm not exactly sure what function they really perform though and if a browser actually makes good use of them. The spec is very clear about what happens to tokens and the parse tree when these parse errors occur, so it seems to add little value to have an actual error value. For now, I will leave them, but I may want to have some code the removes them with a generator or something.

Also, many of the errors in the parse tree section just say "this is a parse error". The test cases that were pulled from webkit suggest these general parse errors have names, like they do in the tokenizer stages. However, I can't find them. Eventually, we will need to revisit these errors and make sure they are accurate, and named properly otherwise the error values will definitely not provide much utility. Currently, all errors that I don't know the names of are "generalParseError".

**Comment by jacobrheath** [comment]
Ok, I am getting rid of this

**Comment by heathj** [comment]
https://github.com/heathj/gobrowse/commit/f10c806b442947b0f81d57611f92bddeec933be7
