### ISSUE TITLE
What is the best way to prioritize these features?

### ISSUE THREAD

**Issue by heathj** [heathj/gobrowse#4]
Much of the spec is full of language that seems to handle odd edge cases, which I probably don't care to support right off the bat. How should I go about getting a "working solution" to build off of, considering I don't really know which of the features are important or not?  Here's an example else case:

> If the synchronous custom elements flag is set, then run these steps while catching any exceptions: 

I'm not sure what synchronous custom elements are used for, but I assume they are related to custom elements and I don't think that should be prioritized.

**Comment by jacobheath** [comment]
PS C:\Users\JHeath\go\src\browser> go test browser/parser -run TestTree -v
=== RUN   TestTreeConstructor
=== RUN   TestTreeConstructor/<!DOCTYPE_html><html><head></head><body><b>JAKE</b></body></html>
=== PAUSE TestTreeConstructor/<!DOCTYPE_html><html><head></head><body><b>JAKE</b></body></html>
=== CONT  TestTreeConstructor/<!DOCTYPE_html><html><head></head><body><b>JAKE</b></body></html>
token Token: DOCTYPE token
        TagName: "html"
        ForQuirks: false
        PublicID: "MISSING"
        SystemID: "MISSING"

reprocess: false, mode: beforeHTML
token Token: startTagToken:
        TagName: "html"
        Attributes: map[]
        SelfClosing: false

reprocess: false, mode: beforeHead
token Token: startTagToken:
        TagName: "head"
        Attributes: map[]
        SelfClosing: false

reprocess: false, mode: inHead
token Token: endTagToken:
        TagName: "head"
        Attributes: map[]
        SelfClosing: false

reprocess: false, mode: afterHead
token Token: startTagToken:
        TagName: "body"
        Attributes: map[]
        SelfClosing: false

reprocess: false, mode: inBody
token Token: startTagToken:
        TagName: "b"
        Attributes: map[]
        SelfClosing: false

reprocess: false, mode: inBody
token Token: characterToken:
        Data: "J"

reprocess: false, mode: inBody
token Token: characterToken:
        Data: "A"

reprocess: false, mode: inBody
token Token: characterToken:
        Data: "K"

reprocess: false, mode: inBody
token Token: characterToken:
        Data: "E"

reprocess: false, mode: inBody
token Token: endTagToken:
        TagName: "b"
        Attributes: map[]
        SelfClosing: false

reprocess: false, mode: inBody
token Token: endTagToken:
        TagName: "body"
        Attributes: map[]
        SelfClosing: false

reprocess: false, mode: inBody
token Token: endTagToken:
        TagName: "html"
        Attributes: map[]
        SelfClosing: false

reprocess: false, mode: inBody
token Token: EofToken

reprocess: false, mode: initial
done
--- PASS: TestTreeConstructor (0.00s)
    --- PASS: TestTreeConstructor/<!DOCTYPE_html><html><head></head><body><b>JAKE</b></body></html> (0.00s)
PASS
ok      browser/parser  0.195s
